# Script to compute the counts (and averages over the years) necessary to
# populate the supplementary tables of the paper.
year_counts_dem = function(df,adm_type,extra_var){
  # df: data.frame from where to compute the counts
  # adm_type: either diagnosis or procedures.
  # extra_var: extra variable to do the grouping
  
  # Function that computes yearly counts for diagnoses or procedures, 
  # adding an extra grouping variable (age, gender, etc.).
  if(adm_type == "diagnosis"){
    df_count = df %>%
      filter(prim == 1) %>%
      filter(adm_year <= "2021" & adm_year >= "2016") %>%
      group_by(adm_year,{{extra_var}}) %>%
      summarize(adm_count = n()) %>%
      ungroup() 
  } else if(adm_type == "procedure"){
    df_count = df %>%
      filter(adm_year <= "2021" & adm_year >= "2016") %>%
      group_by(adm_year,{{extra_var}}) %>%
      summarize(adm_count = n()) %>%
      ungroup() 
  }
  return(df_count)
}
year_counts_dem_percentage = function(df,adm_type,extra_var,N){
  # df: data.frame from where to compute the counts
  # adm_type: either diagnosis or procedures.
  # extra_var: extra variable to do the grouping
  # N: data.frame with the total year counts per year. Each row corresponds
  # to one diagnosis/procedure.
  
  # Function that adds the percentage to the count (percentage over
  # all the admissions in the year)
  year_counts = year_counts_dem(df,adm_type,{{extra_var}})
  N_year = as.data.frame(cbind('adm_year'=as.numeric(colnames(N)),'N'=as.numeric(N[1,])))
  df = year_counts %>%
    left_join(N_year,by = "adm_year") %>%
    mutate(percentage = format(round(adm_count / N *100,2),nsmall = 2)) %>%
    mutate(value = paste(adm_count," (",percentage,")",sep = "")) 
  return(df)
}
generate_avg_dem = function(df,category){
  # df: data.frame with the original counts generated by data_extraction_monthly.R
  # category: each of the categories we group by (Age, Gender, etc.).
  
  # Function that computes the average values
  df_avg = df %>%
    mutate(year = if_else(adm_year >= 2016 & adm_year <= 2019,'2016/19','2020/21')) %>%
    group_by(year,group) %>%
    summarise(avg_count = mean(adm_count),
              avg_N = mean(N)) %>%
    mutate(percentage = format(round(avg_count / avg_N *100,2),nsmall = 2)) %>%
    mutate(value = paste(avg_count," (",percentage,")",sep = "")) 
  
  K = length(levels(as.factor(df_avg$group)))
  final_avg = as.data.frame(matrix(0,ncol=2,nrow=K))
  colnames(final_avg) = c("2016/19","2020/21")
  rownames(final_avg) = levels(as.factor(df_avg$group))
  final_avg[,1] = df_avg$value[1:K]
  final_avg[,2] = df_avg$value[(K+1):(2*K)]
  
  final_df = rbind(rep(NA,2),final_avg)
  rownames(final_df) = c(category,rownames(final_avg))
  return(final_df)
}
generate_avg_dem_v2 = function(df,category){
  # df: data.frame with the original counts generated by data_extraction_monthly.R
  # category: each of the categories we group by (Age, Gender, etc.).
  
  # Function that computes the average values. Modified version that now
  # fills with 0's the categories that did not appear.
  df_avg = df %>%
    mutate(year = if_else(adm_year >= 2016 & adm_year <= 2019,'2016/19','2020/21')) %>%
    group_by(year,group) %>%
    summarise(avg_count = mean(adm_count),
              avg_N = mean(N)) %>%
    mutate(percentage = format(round(avg_count / avg_N *100,2),nsmall = 2)) %>%
    mutate(value = paste(avg_count," (",percentage,")",sep = "")) 
  
  K = length(levels(as.factor(df_avg$group)))
  base_df = as.data.frame(matrix(0,ncol=2,nrow=K))
  base_df[,1] = levels(as.factor(df_avg$group))
  base_df[,2] = rep("base",K)
  colnames(base_df) = c("group","status")
  
  final_avg = as.data.frame(matrix(0,ncol=3,nrow=K))
  colnames(final_avg) = c("group","2016/19","2020/21")
  final_avg[,1] = levels(as.factor(df_avg$group))
  rownames(final_avg) = levels(as.factor(df_avg$group))
  
  for(i in 1:K){
    current_group = final_avg[i,1]
    current_value_position_1619 = which(df_avg$year == "2016/19" & df_avg$group == current_group)
    current_value_position_2021 = which(df_avg$year == "2020/21" & df_avg$group == current_group)
    if(length(current_value_position_1619) != 0){
      final_avg[current_group,2] = df_avg$value[current_value_position_1619]
    } else {
      final_avg[current_group,2] = "0 (0.00)"
    }
    if(length(current_value_position_2021) != 0){
      final_avg[current_group,3] = df_avg$value[current_value_position_2021]
    } else {
      final_avg[current_group,3] = "0 (0.00)"
    }
  }
  final_avg = final_avg %>%
    select(-group)
  
  final_df = rbind(rep(NA,2),final_avg)
  rownames(final_df) = c(category,rownames(final_avg))
  return(final_df)
}
table_avg_dem = function(df,adm_type,N_global,row_name){
  df_gender = year_counts_dem_percentage(df,adm_type,gender,N_global)
  df_age = year_counts_dem_percentage(df,adm_type,age_group,N_global)
  df_ethnicity = year_counts_dem_percentage(df,adm_type,ethnic_group,N_global)
  df_charlson = year_counts_dem_percentage(df,adm_type,Charlson_index,N_global)
  
  colnames(df_gender)[2] = "group"
  colnames(df_age)[2] = "group"
  colnames(df_ethnicity)[2] = "group"
  colnames(df_charlson)[2] = "group"
  
  df_final_year = rbind(df_gender,df_age,df_ethnicity,df_charlson)
  df_final_year_v2 = as.data.frame(rbind(rep(NA,6),df_final_year))
  rownames(df_final_year_v2) = c(row_name,rownames(df_final_year))
  
  summary_gender = generate_avg_dem_v2(df_gender,"Gender")
  summary_age = generate_avg_dem_v2(df_age,"Age (years)")
  summary_ethnicity = generate_avg_dem_v2(df_ethnicity,"Ethnicity")
  summary_charlson = generate_avg_dem_v2(df_charlson,"Charlson index")
  
  final_summary = rbind(summary_gender,summary_age,summary_ethnicity,summary_charlson)
  final_summary_v2 = as.data.frame(rbind(rep(NA,2),final_summary))
  rownames(final_summary_v2) = c(row_name,rownames(final_summary))
  final_summary_v3 = as.data.frame(cbind(rownames(final_summary_v2),final_summary_v2))
  rownames(final_summary_v3) = NULL
  
  return(list('dem_year' = df_final_year_v2,'dem_year_avg'= final_summary_v3))
}

# Read the total number of admissions per year (necessary for computing the %),
# that have been computed using Table1_year_avg.R.
setwd("~/CCU003_04/Jun2022/Outputs")
avg_global_counts = read.csv("all_year_count.csv",stringsAsFactors = F,header = F)
colnames(avg_global_counts) = avg_global_counts[1,]
avg_global_counts = avg_global_counts[-1,]
rownames(avg_global_counts) = avg_global_counts[,1]
avg_global_counts = avg_global_counts[,-1]

# Generate each subtable with all the groups for each of the diagnosis/procedures.
setwd("~/CCU003_04/Jun2022/results")
ACS = read.csv("results_IHD_monthly.csv", stringsAsFactors = F)[,-1] %>%
  mutate(Charlson_index = case_when(Charlson_score == 0 ~ '0',
                                    Charlson_score == 1 ~ '1',
                                    Charlson_score == 2 ~ '2',
                                    Charlson_score >= 3 ~ '3+'))
table01 = table_avg_dem(ACS,"diagnosis",avg_global_counts[1,],"ACS")
table01_year = table01[[1]]
table01_avg = table01[[2]]

ACS_proc = read.csv("results_IHD_proc_monthly.csv", stringsAsFactors = F)[,-1] %>%
  mutate(Charlson_index = case_when(Charlson_score == 0 ~ '0',
                                    Charlson_score == 1 ~ '1',
                                    Charlson_score == 2 ~ '2',
                                    Charlson_score >= 3 ~ '3+'))
ACS_proc1 = ACS_proc %>%
  filter(strata == "Percutaneous")
ACS_proc2 = ACS_proc %>%
  filter(strata == "Bypass")
table02 = table_avg_dem(ACS_proc1,"procedure",avg_global_counts[2,],"Percutaneous")
table02_year = table02[[1]]
table02_avg = table02[[2]]

table03 = table_avg_dem(ACS_proc2,"procedure",avg_global_counts[3,],"Bypass")
table03_year = table03[[1]]
table03_avg = table03[[2]]

HF = read.csv("results_HF_monthly.csv", stringsAsFactors = F)[,-1] %>%
  mutate(Charlson_index = case_when(Charlson_score == 0 ~ '0',
                                    Charlson_score == 1 ~ '1',
                                    Charlson_score == 2 ~ '2',
                                    Charlson_score >= 3 ~ '3+'))
table04 = table_avg_dem(HF,"diagnosis",avg_global_counts[4,],"HF")
table04_year = table04[[1]]
table04_avg = table04[[2]]

HF_proc = read.csv("results_HF_proc_monthly.csv", stringsAsFactors = F)[,-1] %>%
  mutate(Charlson_index = case_when(Charlson_score == 0 ~ '0',
                                    Charlson_score == 1 ~ '1',
                                    Charlson_score == 2 ~ '2',
                                    Charlson_score >= 3 ~ '3+'))
HF_proc1 = HF_proc %>%
  filter(strata == "Pacemaker")
HF_proc2 = HF_proc %>%
  filter(strata == "Transplant")
table05 = table_avg_dem(HF_proc1,"procedure",avg_global_counts[5,],"Pacemaker")
table05_year = table05[[1]]
table05_avg = table05[[2]]

table06 = table_avg_dem(HF_proc2,"procedure",avg_global_counts[6,],"Transplant")
table06_year = table06[[1]]
table06_avg = table06[[2]]

AS = read.csv("results_AS_monthly.csv", stringsAsFactors = F)[,-1] %>%
  mutate(Charlson_index = case_when(Charlson_score == 0 ~ '0',
                                    Charlson_score == 1 ~ '1',
                                    Charlson_score == 2 ~ '2',
                                    Charlson_score >= 3 ~ '3+'))
table07 = table_avg_dem(AS,"diagnosis",avg_global_counts[7,],"Stroke")
table07_year = table07[[1]]
table07_avg = table07[[2]]

AS_proc = read.csv("results_AS_proc_monthly.csv", stringsAsFactors = F)[,-1] %>%
  mutate(Charlson_index = case_when(Charlson_score == 0 ~ '0',
                                    Charlson_score == 1 ~ '1',
                                    Charlson_score == 2 ~ '2',
                                    Charlson_score >= 3 ~ '3+'))
AS_proc1 = AS_proc %>%
  filter(strata == "Thrombo")
AS_proc2 = AS_proc %>%
  filter(strata == "Carotid")
AS_proc3 = AS_proc %>%
  filter(strata == "Cerebral")

table08 = table_avg_dem(AS_proc1,"procedure",avg_global_counts[8,],"Thrombo")
table08_year = table08[[1]]
table08_avg = table08[[2]]

table09 = table_avg_dem(AS_proc2,"procedure",avg_global_counts[9,],"Carotid")
table09_year = table09[[1]]
table09_avg = table09[[2]]

table10 = table_avg_dem(AS_proc3,"procedure",avg_global_counts[10,],"Cerebral")
table10_year = table10[[1]]
table10_avg = table10[[2]]

AA = read.csv("results_AA_monthly.csv", stringsAsFactors = F)[,-1] %>%
  mutate(Charlson_index = case_when(Charlson_score == 0 ~ '0',
                                    Charlson_score == 1 ~ '1',
                                    Charlson_score == 2 ~ '2',
                                    Charlson_score >= 3 ~ '3+'))
table11 = table_avg_dem(AA,"diagnosis",avg_global_counts[11,],"AA")
table11_year = table11[[1]]
table11_avg = table11[[2]]

AA_proc = read.csv("results_AA_proc_monthly.csv", stringsAsFactors = F)[,-1] %>%
  mutate(Charlson_index = case_when(Charlson_score == 0 ~ '0',
                                    Charlson_score == 1 ~ '1',
                                    Charlson_score == 2 ~ '2',
                                    Charlson_score >= 3 ~ '3+'))
table12 = table_avg_dem(AA_proc,"procedure",avg_global_counts[12,],"AA repair")
table12_year = table12[[1]]
table12_avg = table12[[2]]

PAD = read.csv("results_PAD_monthly.csv", stringsAsFactors = F)[,-1] %>%
  mutate(Charlson_index = case_when(Charlson_score == 0 ~ '0',
                                    Charlson_score == 1 ~ '1',
                                    Charlson_score == 2 ~ '2',
                                    Charlson_score >= 3 ~ '3+'))
table13 = table_avg_dem(PAD,"diagnosis",avg_global_counts[13,],"PAD")
table13_year = table13[[1]]
table13_avg = table13[[2]]

PAD_proc = read.csv("results_PAD_proc_monthly.csv", stringsAsFactors = F)[,-1] %>%
  mutate(Charlson_index = case_when(Charlson_score == 0 ~ '0',
                                    Charlson_score == 1 ~ '1',
                                    Charlson_score == 2 ~ '2',
                                    Charlson_score >= 3 ~ '3+'))
PAD_proc1 = PAD_proc %>%
  filter(strata == "Angioplasty")
PAD_proc2 = PAD_proc %>%
  filter(strata == "Revascular")
table14 = table_avg_dem(PAD_proc1,"procedure",avg_global_counts[14,],"Angioplasty")
table14_year = table14[[1]]
table14_avg = table14[[2]]

table15 = table_avg_dem(PAD_proc2,"procedure",avg_global_counts[15,],"Revascular")
table15_year = table15[[1]]
table15_avg = table15[[2]]

VTE = read.csv("results_VTE_monthly.csv", stringsAsFactors = F)[,-1] %>%
  mutate(Charlson_index = case_when(Charlson_score == 0 ~ '0',
                                    Charlson_score == 1 ~ '1',
                                    Charlson_score == 2 ~ '2',
                                    Charlson_score >= 3 ~ '3+'))
table16 = table_avg_dem(VTE,"diagnosis",avg_global_counts[16,],"VTE")
table16_year = table16[[1]]
table16_avg = table16[[2]]

VTE_proc = read.csv("results_VTE_proc_monthly.csv", stringsAsFactors = F)[,-1] %>%
  mutate(Charlson_index = case_when(Charlson_score == 0 ~ '0',
                                    Charlson_score == 1 ~ '1',
                                    Charlson_score == 2 ~ '2',
                                    Charlson_score >= 3 ~ '3+'))
table17 = table_avg_dem(VTE_proc,"procedure",avg_global_counts[17,],"VTE repair")
table17_year = table17[[1]]
table17_avg = table17[[2]]

# Join the different tables:
tables_year = c(paste("table0",1:9,"_year",sep=""),paste("table",10:17,"_year",sep=""))
N = length(tables_year)
super_year_table = get(tables_year[1])
for(i in 2:N){
  super_year_table = rbind(super_year_table,get(tables_year[i]))
}

tables_avg = c(paste("table0",1:9,"_avg",sep=""),paste("table",10:17,"_avg",sep=""))
N = length(tables_avg)
super_avg_table = get(tables_avg[1])
for(i in 2:N){
  super_avg_table = rbind(super_avg_table,get(tables_avg[i]))
}
# Save tables with all the numbers
setwd("~/CCU003_04/Jun2022/Outputs")
write.csv(super_year_table,"SupTable_year.csv")
write.csv(super_avg_table,"SupTable_avg.csv")
 
# Clean tables so there are not <5 counts in a cell:
super_year_table_clean = super_year_table
less_5 = which(!is.na(super_year_table_clean$adm_count) & super_year_table_clean$adm_count <= 5)
super_year_table_clean$adm_count = as.character(super_year_table_clean$adm_count)
super_year_table_clean[less_5,3] = "<5"
super_year_table_clean[less_5,4:6] = c(NA,NA,NA)

write.csv(super_year_table_clean,"SupTable_year_clean.csv")

super_avg_table_clean = super_avg_table
less_5_1619 = which(!is.na(super_avg_table_clean[,2]) & parse_number(super_avg_table_clean[,2]) <= 5)
less_5_2021 = which(!is.na(super_avg_table_clean[,3]) & parse_number(super_avg_table_clean[,3]) <= 5)
#super_year_table_clean[,2:3] = as.character(super_year_table_clean[,2:3])
super_avg_table_clean[less_5_1619,2] = "<5"
super_avg_table_clean[less_5_2021,3] = "<5"

write.csv(super_avg_table_clean,"SupTable_avg_clean.csv")
